tela = input('Digite algo:')

print('O tipo primitivo desse valor é', type(tela))
print('tem espaços?', tela.isspace())
print('é um numero?', tela.isnumeric())
print('é alfabético?', tela.isalpha())
print('é alfanumerio?', tela.isalnum())
print('esta em maiusculas?', tela.isupper())
print('esta em minusculas?', tela.islower())
print('esta capitalizada?', tela.istitle())